package GUI;

import LogicaDeNegocios.Validador;
import it.ssc.pl.milp.LP;
import it.ssc.pl.milp.Solution;
import it.ssc.pl.milp.SolutionType;
import it.ssc.pl.milp.Variable;
import it.ssc.ref.InputString;
import java.awt.Image;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yurledy Fernanda Perez
 * @author Andres Felipe Narvaez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MinimoMaximos = new javax.swing.ButtonGroup();
        ContenedorVentana = new javax.swing.JPanel();
        ContenedorEncabezado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ContenedorIzquierdo = new javax.swing.JPanel();
        Separador1 = new javax.swing.JSeparator();
        Texto1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Campo1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Campo2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ComboDeRestricciones = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        BotonConfirmacion = new javax.swing.JButton();
        ContenedorDerecho = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ResultadoFO = new javax.swing.JTextField();
        ResultadoX1 = new javax.swing.JTextField();
        ResultadoX2 = new javax.swing.JTextField();
        BotonReiniciar = new javax.swing.JButton();
        ContenedorPie = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo Simplex");
        setResizable(false);

        ContenedorVentana.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorEncabezado.setBackground(new java.awt.Color(102, 102, 102));
        ContenedorEncabezado.setVerifyInputWhenFocusTarget(false);

        Image img2 = new ImageIcon(getClass().getResource("/Imagenes/profesor.png")).getImage();
        Image newimg2 = img2.getScaledInstance(100, 90,  java.awt.Image.SCALE_SMOOTH);
        ImageIcon imageIcon2 = new ImageIcon(newimg2);
        //asigna a componenente JLabel
        jLabel6.setIcon(imageIcon2);

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SOLUCIONADOR DE PROBLEMAS DE PROGRAMACION LINEAL");

        javax.swing.GroupLayout ContenedorEncabezadoLayout = new javax.swing.GroupLayout(ContenedorEncabezado);
        ContenedorEncabezado.setLayout(ContenedorEncabezadoLayout);
        ContenedorEncabezadoLayout.setHorizontalGroup(
            ContenedorEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorEncabezadoLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224)
                .addComponent(jLabel8)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        ContenedorEncabezadoLayout.setVerticalGroup(
            ContenedorEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorEncabezadoLayout.createSequentialGroup()
                .addGroup(ContenedorEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorEncabezadoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8))
                    .addGroup(ContenedorEncabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContenedorIzquierdo.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorIzquierdo.setPreferredSize(new java.awt.Dimension(550, 500));

        Separador1.setBackground(new java.awt.Color(153, 153, 153));

        Texto1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Texto1.setText("DATOS DEL MODELO MATEMATICO");

        jLabel2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel2.setText("Digite la funcion objetivo");

        jLabel3.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel3.setText("Z(X1,X2)=");

        Campo1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        Campo1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel4.setText("X1 + ");

        Campo2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel5.setText("X2");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        MinimoMaximos.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jRadioButton1.setText("Min");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setActionCommand("min");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        MinimoMaximos.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jRadioButton2.setText("Max");
        jRadioButton2.setActionCommand("max");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad de restricciones");

        ComboDeRestricciones.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        ComboDeRestricciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        ComboDeRestricciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboDeRestriccionesItemStateChanged(evt);
            }
        });

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "X1", "X2", "Simbolo", "Constante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaDatos);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        BotonConfirmacion.setText("Encontrar Solucion");
        BotonConfirmacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorIzquierdoLayout = new javax.swing.GroupLayout(ContenedorIzquierdo);
        ContenedorIzquierdo.setLayout(ContenedorIzquierdoLayout);
        ContenedorIzquierdoLayout.setHorizontalGroup(
            ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                .addGroup(ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separador1))
                    .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addGap(47, 47, 47))
                            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                        .addGroup(ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(Texto1))
                            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)))
                            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(ComboDeRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(BotonConfirmacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContenedorIzquierdoLayout.setVerticalGroup(
            ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorIzquierdoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Texto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ContenedorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboDeRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonConfirmacion)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ContenedorDerecho.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("RESULTADOS");

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Z(X1,X2)=");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("X1=");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("X2=");

        ResultadoFO.setEditable(false);
        ResultadoFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoFOActionPerformed(evt);
            }
        });

        ResultadoX1.setEditable(false);

        ResultadoX2.setEditable(false);

        BotonReiniciar.setText("Reiniciar");
        BotonReiniciar.setEnabled(false);
        BotonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorDerechoLayout = new javax.swing.GroupLayout(ContenedorDerecho);
        ContenedorDerecho.setLayout(ContenedorDerechoLayout);
        ContenedorDerechoLayout.setHorizontalGroup(
            ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                        .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jLabel9))
                            .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(42, 42, 42)
                                .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultadoFO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultadoX1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultadoX2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(BotonReiniciar)))
                        .addGap(0, 195, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContenedorDerechoLayout.setVerticalGroup(
            ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ResultadoFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ResultadoX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(ContenedorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ResultadoX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(BotonReiniciar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        ContenedorPie.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout ContenedorPieLayout = new javax.swing.GroupLayout(ContenedorPie);
        ContenedorPie.setLayout(ContenedorPieLayout);
        ContenedorPieLayout.setHorizontalGroup(
            ContenedorPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        ContenedorPieLayout.setVerticalGroup(
            ContenedorPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout ContenedorVentanaLayout = new javax.swing.GroupLayout(ContenedorVentana);
        ContenedorVentana.setLayout(ContenedorVentanaLayout);
        ContenedorVentanaLayout.setHorizontalGroup(
            ContenedorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorVentanaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(ContenedorIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContenedorVentanaLayout.createSequentialGroup()
                .addGroup(ContenedorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenedorEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContenedorPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ContenedorVentanaLayout.setVerticalGroup(
            ContenedorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorVentanaLayout.createSequentialGroup()
                .addComponent(ContenedorEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContenedorVentanaLayout.createSequentialGroup()
                        .addGroup(ContenedorVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContenedorIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContenedorDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContenedorPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenedorVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenedorVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ComboDeRestriccionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboDeRestriccionesItemStateChanged
        DefaultTableModel modelo = (DefaultTableModel) TablaDatos.getModel();
        modelo.setRowCount(ComboDeRestricciones.getSelectedIndex() + 1);
        TablaDatos.setModel(modelo);

    }//GEN-LAST:event_ComboDeRestriccionesItemStateChanged

    private void BotonConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmacionActionPerformed
        validador = new Validador();
        validador.validarTabla(TablaDatos);
        validador.validarCampos(Campo1, Campo2);
        validador.validarGrupoBoton(MinimoMaximos);

        if (validador.isFlag()) {
            String lp_string = "" + Campo1.getText() + " " + Campo2.getText()
                    + " " + MinimoMaximos.getSelection().getActionCommand() + " . \n";

            String[][] matriz = validador.getMatriz();
            for (int i = 0; i < matriz.length; i++) {
                for (int j = 0; j < 4; j++) {
                    lp_string += matriz[i][j] + " ";
                }
                lp_string += "\n";
            }

            System.out.println(lp_string);

            InputString lp_input = new InputString(lp_string);
            try {
                lp_input.setInputFormat("X1:double, X2:double, TYPE:varstring(3), RHS:double");
                LP lp = new LP(lp_input);
                SolutionType solution_type = lp.resolve();
                if (solution_type == SolutionType.OPTIMUM) {
                    Variable[] vdd = new Variable[2];
                    double[] desicion = new double[2];
                    Solution solution = lp.getSolution();
                    vdd = solution.getVariables();
                    for (int i = 0; i < vdd.length; i++) {
                        desicion[i] = vdd[i].getValue();
                    }
                    DecimalFormat df = new DecimalFormat("#.000");
                    ResultadoX1.setText("" + df.format(desicion[0]));
                    ResultadoX2.setText("" + df.format(desicion[1]));
                    ResultadoFO.setText("" + df.format(solution.getOptimumValue()));
                    BotonReiniciar.setEnabled(true);
                    BotonConfirmacion.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "SE HA ENCONTRADO UNA SOLUCION OPTIMA");
                } else {
                    JOptionPane.showMessageDialog(null, "NO SE HA ENCONTRADO UNA SOLUCION OPTIMA");
                }

            } catch (Exception ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "¡INCONSISTENCIA EN LOS DATOS, POR FAVOR REVISAR!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonConfirmacionActionPerformed

    private void ResultadoFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoFOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoFOActionPerformed

    private void BotonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReiniciarActionPerformed
        Campo1.setText("");
        Campo2.setText("");
        MinimoMaximos.clearSelection();
        ComboDeRestricciones.setSelectedIndex(0);
        BotonReiniciar.setEnabled(false);
        BotonConfirmacion.setEnabled(true);
        ResultadoFO.setText("");
        ResultadoX1.setText("");
        ResultadoX2.setText("");
        DefaultTableModel temp = (DefaultTableModel) TablaDatos.getModel();
        int filas = TablaDatos.getRowCount();
        for (int a = 0; filas > a; a++) {
            temp.removeRow(0);
        }
        temp.setRowCount(1);
        TablaDatos.setModel(temp);

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonReiniciarActionPerformed

    private boolean esEntero(double a) {
        if (a % 1 == 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirmacion;
    private javax.swing.JButton BotonReiniciar;
    private javax.swing.JTextField Campo1;
    private javax.swing.JTextField Campo2;
    private javax.swing.JComboBox<String> ComboDeRestricciones;
    private javax.swing.JPanel ContenedorDerecho;
    private javax.swing.JPanel ContenedorEncabezado;
    private javax.swing.JPanel ContenedorIzquierdo;
    private javax.swing.JPanel ContenedorPie;
    private javax.swing.JPanel ContenedorVentana;
    private javax.swing.ButtonGroup MinimoMaximos;
    private javax.swing.JTextField ResultadoFO;
    private javax.swing.JTextField ResultadoX1;
    private javax.swing.JTextField ResultadoX2;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    private Validador validador;

}
